readmeio/standards

index.js
package-lock.json
package.json

Lints will now do verification checks on existing `eslint-disable` rules, using [eslint-plugin-eslint-comments](https://www.npmjs.com/package/eslint-plugin-eslint-comments), to assert that we aren't disabling **everything** in a given file or line.
We're now also using [eslint-plugin-node](https://www.npmjs.com/package/eslint-plugin-node) to verify that we aren't:
* Using deprecated APIs: https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-deprecated-api.md
* Improperly using `exports`: https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-exports-assign.md
* Using extraneous `require` statements: https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-extraneous-require.md

Expanding our ruleset to include expanded checks

---

package-lock.json
package.json

It's kind of ardous to manage peerdeps independently of this since when those peerdeps are bumped, they should be bumped as a whole with this config. This'll also mean that every repo that uses this gets less dependabot spam.

Removing peerdeps in favor of explicit deps

---

package-lock.json
package.json
testing.js

This loads in the [eslint-plugin-jest-formatting](https://npm.im/eslint-plugin-jest-formatting) package to enforce a consistent set of rules around how Jest tests should be styled.
This also resolves an issue where the `jest/expect-expect` rule was set to `warn` instead of `error`.

Enforcing consistent formatting of Jest tests

---

.github/workflows/nodejs.yml
index.js

Having this in our core ESLint config will allow us to stop requiring `.pretteirrc` files in every repository.

feat: including our standard prettier config so it can be shared

---

README.md
index.js
package-lock.json
prettier.js

feat: exporting our prettier config

---

.prettierrc

Updates our Prettier config to address an issue where `npm test -- -u` would auto-convert unicode strings _back_ to emojis in our scripts, which caused breakage in IE11 (See: [api-explorer#e357013](https://github.com/readmeio/api-explorer/pull/687/commits/e357013dbf2a6abb3bbb4dee99263884c285069f)) Alternately, we could probably override this directly in the Explorer somehow; no opinion on which'd be better...

quote JS object properties consistently

---

package-lock.json
package.json
react.js

This pulls [eslint-plugin-react-hooks](https://www.npmjs.com/package/eslint-plugin-react-hooks) into our react config to ensure that we're not violating the [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html).

feat: pulling eslint-plugin-react-hooks into our react config

---

package-lock.json
package.json
testing.js

Added these two plugins:
- [eslint-plugin-testing-library](https://github.com/testing-library/eslint-plugin-testing-library)
- [eslint-plugin-jest-dom](https://github.com/testing-library/eslint-plugin-jest-dom)
I was thinking of making this a separate `ui-testing.js` file, but changed my mind because it felt like it'd be annoying to have two different places to manage our Jest rules. Totally open to discussion on this.

feat: add testing-library plugins to testing config

---

testing.js

Adapted from the plugin [docs](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/consistent-test-it.md):
```
/*eslint jest/consistent-test-it: ["error", {"fn": "test", "withinDescribe": "it"}]*/
test('foo'); // valid
describe('foo', function () {
it('bar'); // valid
});
it('foo'); // invalid
describe('foo', function () {
test('bar'); // invalid
});
```

feat: prefer bare test and nested it

---

index.js

Nested ternary statements can provide a nice, clean pattern for writing complex if/else-if/else logic in JSX:
```jsx
{isLoading ? (
<Spinner />
) : !data?.length ? (
<Flex justify="center">No results.</Flex>
) : (
<Table body={data} />
)}
```
But this syntax throws a lint error in the React app! Instead, you'd be forced to write something ugly, like:
```jsx
{tableIsLoading ? (
<Spinner style={{ color: "var(--shale)" }} />
) : (
(!table?.length && <Flex justify="center">No data found.</Flex>) || (
<Table body={table || []} />
)
)}
```
If you can write a nested ternary in your JSX without the linter throwing a fit, this worked!

chore: allow nested ternary statements

---

.github/workflows/ci.yml
package-lock.json
package.json

Installing this library with npm@8 generates a warning that it actually wants npm@7. Since either work, and the npm requirement is only really there for local development I'm removing it.
And in order to make sure that the library still works okay without this on Node 12 and Node 14 I'm updating our CI workflow to install npm@8 on these versions. This is unnecessary on Node 16 because Node 16 ships with npm@8 already.

feat: loosening up the npm engine requirements to easily allow npm@8

---

index.js
package-lock.json

Enables `import/no-anonymous-default-export`.
https://twitter.com/addyosmani/status/1471743877916737537
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-anonymous-default-export.md

feat: enabling `import/no-anonymous-default-export`

---

README.md
package-lock.json
package.json
testing-mocha.js

We've started using Mocha + Chai in `fetch-har` so we can run the same test in the browser, and as a result came upon a new config for this. Since we'll likely be using this setup in more open source repos that need browser testing I'm pulling it in here so we can share it across our projects.

feat: mocha testing config

---

typescript.js

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-indexed-object-style.md

fix: requiring consistency of typescript record types

---

typescript.js

Slightly tweaks our `no-use-before-define` rule usage in the TS config to allow TS types that can be used before they're defined without errors.
For example, without this rule change the following code was throwing an error on `ConfigOptions` being used before it was defined even though TS is perfectly fine with where it's located in the file.:
```ts
import Oas from 'oas';
import APICore from './src/core';
import definition from './test/__fixtures__/simple.oas.json';
export default class SDK {
spec: Oas;
core: APICore;
authKeys: (number | string)[][] = [];
constructor() {
this.spec = Oas.init(definition);
this.core = new APICore(this.spec, 'api/1.0.0');
}
config(config: ConfigOptions) {
this.core.setConfig(config);
}
}
interface ConfigOptions {
/**
* By default we parse the response based …
```

feat: tweaking our use of the `no-use-before-define` rule in TS

---

package-lock.json
package.json

ESLint deps being in the root `package.json` file are currently breaking ESLint in CI: https://github.com/readmeio/standards/runs/5824177810?check_suite_focus=true

fix: dep issues with the root package.json that's breaking eslint

---

package.json

| 🚥 Fix RM-XXX |
| :-- |
Reference to Lerna's lifecycle sequence:
https://github.com/lerna/lerna/tree/main/commands/version#lifecycle-scripts
When Lerna independently bumps new versions for all *changed* packages,
the root `package-lock.json` file also needs to be updated for
record-keeping. Otherwise, CI checks will fail. However Lerna does not
do this automatically for us.
Step 4 in the versioning sequence is where we add a custom step to
update our `package-lock.json` by running an `npm install` and then
immediately staging it. Step 5 and 6 will then include it when issuing
the commit. 🎉
Provide as much information as you can on how to test what you've done.

chore: add "version" step to keep package-lock in sync

---

packages/eslint-config/typescript.js

| 🚥 Fix RM-XXX |
| :-- |
Issue reference:
https://github.com/typescript-eslint/typescript-eslint/issues/2483
Fixes the false-positive error when declaring enums like this:
```ts
export enum Type {
Dialog = 'dialog',
ActionSheet = 'actionSheet',
}
```
Provide as much information as you can on how to test what you've done.

fix(eslint-config): fix false-positive error with TS enums

---

packages/stylelint-config/__tests__/__snapshots__/index.js.snap
packages/stylelint-config/__tests__/index.js
packages/stylelint-config/__tests__/invalid.scss
packages/stylelint-config/__tests__/valid.scss
packages/stylelint-config/index.js

| 🚥 Fix RM-XXX |
| :-- |
ReadMe still has cases where it names and references elements by #id.
So make an exception for that but limit this to at most one ID max per
selector. In other words, never allow something like `#one #two {...}`.
By default, all ids are expected to be kebab-cased. However, ReadMe
still uses TitleCased ids, similar to its Component BEM class name
patterns.
Provide as much information as you can on how to test what you've done.

Update stylelint rules for ReadMe ID selector patterns

---

.github/dependabot.yml
.github/workflows/ci.yml
package-lock.json
packages/spectral-config/.eslintrc
packages/spectral-config/.gitignore
packages/spectral-config/LICENSE
packages/spectral-config/README.md
packages/spectral-config/package-lock.json
packages/spectral-config/package.json
packages/spectral-config/src/functions/alex.js
packages/spectral-config/src/functions/index.js
packages/spectral-config/src/functions/sentencePunctuation.js
packages/spectral-config/src/index.js
packages/spectral-config/src/rules/alex-component-description.js
packages/spectral-config/src/rules/alex-component-summary.js
packages/spectral-config/src/rules/alex-operation-description.js
packages/spectral-config/src/rules/alex-operation-summary.js
packages/spectral-config/src/rules/alex-parameter.js
packages/spectral-config/src/rules/alex-response.js
packages/spectral-config/src/rules/description-sentence-punctuation.js
packages/spectral-config/src/rules/index.js
packages/spectral-config/test/.eslintrc
packages/spectral-config/test/alex-component-description.test.js
packages/spectral-config/test/alex-component-summary.test.js
packages/spectral-config/test/alex-operation-description.test.js
packages/spectral-config/test/alex-operation-summary.test.js
packages/spectral-config/test/alex-parameter.test.js
packages/spectral-config/test/alex-response.test.js
packages/spectral-config/test/description-sentence-punctuation.test.js

I've literally copied this same Spectral config I've been building over the past few months to two different internal repos over the past couple weeks so it's time to make this thing into its own package.
I noticed https://github.com/IBM/openapi-validator/tree/main/packages/ruleset had tests for their own Spectral rules and it looked great, and I didn't want to reinvent the wheel, so I'm pulling that package in to help test everything. We didn't have tests for these rules already, so yay.

feat: publicizing our internal API docs Spectral config

---

packages/stylelint-config/__tests__/__snapshots__/index.js.snap
packages/stylelint-config/__tests__/index.js
packages/stylelint-config/__tests__/invalid.scss
packages/stylelint-config/__tests__/valid.scss
packages/stylelint-config/src/index.js

| 🚥 Fixes ISSUE_ID |
| :---------------- |
Disables the `media-query-no-invalid` rule, which was enabled in the latest `stylelint-config-recommended` extension. We don't want to use it with SCSS.
Provide as much information as you can on how to test what you've done.

fix(stylelint-config): disable media-query-no-invalid rule

---

.github/dependabot.yml
.prettierignore
packages/eslint-config/prettier.js
packages/spectral-config/README.md
packages/stylelint-config/README.md
packages/stylelint-config/package.json

This PR brings back `packages/eslint-config/prettier.js` so the `@readme/eslint-config/prettier` shorthand works again. This PR also does some meta-housekeeping using Prettier:
Does the `@readme/eslint-config/prettier` shorthand work again?

fix: more prettier cleanup

---

packages/spectral-config/package.json
packages/spectral-config/src/functions/alex.js

| 🚥 Resolves ISSUE_ID |
| :------------------- |
Per Jon's suggestion [here](https://github.com/readmeio/standards/pull/724#discussion_r1292443171), I was able to move the `NODE_OPTIONS='--no-deprecation'` that we previously needed for tests by importing `alex/index.js`.
Do tests pass without a bunch of garbage input?

chore(spectral): point `alex` import to `index.js`

---

packages/eslint-config/esm.js

Enables the [`import/no-commonjs`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-commonjs.md) rule in our ESM-specific linting config.

fix(eslint/esm): enable `import/no-commonjs`

---

.prettierignore
package-lock.json
package.json
packages/eslint-config/esm.js
packages/eslint-config/index.js
packages/eslint-config/package.json
packages/eslint-config/prettier.config.js
packages/eslint-config/react.js
packages/eslint-config/testing/common.config.js
packages/eslint-config/testing/jest-dom.js
packages/eslint-config/testing/jest.js
packages/eslint-config/testing/react.js
packages/eslint-config/testing/vitest.js
packages/eslint-config/tsconfig.json
packages/eslint-config/typescript.js

I've been feeling a little uneasy for sometime about the fact that there's no great way in the ESLint ecosystem to validate shared configs like ours. I discovered [`eslint-define-config`](https://github.com/Shinigami92/eslint-define-config) (in lieu of ESLint exporting their own types, which sadly [they've confirmed they have no plans to do](https://github.com/eslint/eslint/issues/14249)) which seems great and well-maintained, so I brought that in and added a little `tsconfig` so we can start type-checking our existing JS files. Hopefully this will make it easier to maintain our configs over time.
Prettier is great and maintains their own types so I also brought those in.
The good (but generally slightly concerning) thing is we don't have any errors that this flagged, but I confirmed …

ci(eslint-config): add lightweight type-checking

---

packages/eslint-config/esm.js

This PR enables two rules in our ESM config:
1. **[`unicorn/prefer-module`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-module.md)** — this came up as a result of https://github.com/readmeio/oas-to-har/pull/243 — this rule will prevent a variety of Node/CommonJS usage patterns, such as `__dirname`, `require`, and `module.exports` _(this rule slaps)_
2. **[`node/no-extraneous-import`](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-extraneous-import.md)** — basically the ESM equivalent of [`node/no-extraneous-require`](https://github.com/mysticatea/eslint-plugin-node/blob/v11.1.0/docs/rules/no-extraneous-require.md)
There are a slew of suggested ESM configuration options listed in [this …

feat(eslint/esm): enable more ESM rules

---

packages/eslint-config/esm.js

In libraries that support CJS and ESM having a default export along with exported types completely breaks CJS handling so we're going to start disabling default exports in ESM libraries we ship.

feat(eslint): disabling default exports in ESM libraries

---

package-lock.json
package.json
packages/eslint-config/index.js
packages/eslint-config/package.json
packages/eslint-config/testing/jest-dom.js
packages/eslint-config/testing/jest.js
packages/eslint-config/testing/vitest.js

We're dropping use of `eslint-plugin-prettier` within our main ESLint config as we've been experiencing some performance setbacks with it in our large codebase. Instead we now recommend running Prettier separately alongside ESLint (which `typescript-eslint` also recommends doing[^1]).
[^1]: https://typescript-eslint.io/troubleshooting/performance-troubleshooting/#eslint-plugin-prettier

feat(eslint-config): dropping use of `eslint-plugin-prettier`

---

package-lock.json
packages/eslint-config/index.js
packages/eslint-config/package.json

This pulls in [eslint-plugin-try-catch-failsafe](https://github.com/RexSkz/eslint-plugin-try-catch-failsafe) in order for us to better catch cases where `JSON.parse()` and `new URL()` aren't wrapped in try-catch blocks.

feat(eslint-config): pulling in `eslint-plugin-try-catch-failsafe`
